version: "2.1"
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    environment:
      - TZ=Etc/GMT+2
    volumes:
      - config:/config
    ports:
      - 8123:8123
    devices:
      - /dev/ttyACM0
    restart: unless-stopped

volumes:
  config:
